services:
  - type: web
    name: meesho-order-manager
    runtime: docker
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PORT
        value: 10000
      - key: HEADLESS
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "1"
